spring.application.name=user_unir
spring.jpa.show-sql=true
spring.jpa.generate-ddl= true
spring.jpa.hibernate.ddl-auto= update
server.port=8081
# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://localhost:5432/taxis_unir
spring.datasource.username= admin
spring.datasource.password= admin123

spring.main.web-application-type=reactive


#EurekaClient
eureka.instance.instance-id=${spring.application.name}:${random.value}